"""
Development Agent
─────────────────
Receives a task from the Kanban backlog and generates:
  • C# backend code (controller + service skeleton)
  • React frontend code (component skeleton)

It then commits both files to GitHub via the integrations layer.
"""
from __future__ import annotations

from agents.base_agent import BaseAgent
from config.settings import LLM_DEV
from integrations.github_integration import GitHubIntegration
from llm import get_provider


class DevelopmentAgent(BaseAgent):
    name = "development"

    def __init__(self) -> None:
        super().__init__()
        self.llm = get_provider(LLM_DEV)
        self.github = GitHubIntegration()

    # ── helpers ───────────────────────────────────────────────────────────────

    def _backend_prompt(self, task: dict) -> str:
        return (
            f"You are an expert C# .NET 8 developer.\n"
            f"Generate a minimal but complete ASP.NET Core Web API controller and its "
            f"corresponding service class for the following user story:\n\n"
            f"Title: {task.get('title', '')}\n"
            f"Description: {task.get('description', '')}\n"
            f"Acceptance criteria:\n{task.get('acceptance_criteria', 'N/A')}\n\n"
            f"Output ONLY valid C# code, no markdown fences."
        )

    def _frontend_prompt(self, task: dict) -> str:
        return (
            f"You are an expert React + TypeScript developer.\n"
            f"Generate a minimal but complete React functional component for:\n\n"
            f"Title: {task.get('title', '')}\n"
            f"Description: {task.get('description', '')}\n\n"
            f"Output ONLY valid TSX code, no markdown fences."
        )

    # ── core logic ────────────────────────────────────────────────────────────

    def execute(self, task: dict) -> dict:
        task_id = str(task.get("id", "unknown"))
        title_slug = task.get("title", "task").lower().replace(" ", "-")[:40]
        branch = f"feature/ai/{task_id}-{title_slug}"

        self.logger.info(f"Generating code for task '{task.get('title')}'")

        # Generate code
        backend_code = self.llm.generate(self._backend_prompt(task))
        frontend_code = self.llm.generate(self._frontend_prompt(task))

        # Determine file paths
        class_name = "".join(w.capitalize() for w in title_slug.split("-"))
        backend_path = f"backend/src/Controllers/{class_name}Controller.cs"
        frontend_path = f"frontend/src/components/{class_name}/{class_name}.tsx"

        # Commit to GitHub
        commit_results = []
        for path, content in [(backend_path, backend_code), (frontend_path, frontend_code)]:
            result = self.github.commit_file(
                branch=branch,
                file_path=path,
                content=content,
                message=f"feat({task_id}): generate {path.split('/')[-1]}",
            )
            commit_results.append(result)

        # Open Pull Request
        pr = self.github.create_pull_request(
            branch=branch,
            title=f"[AI] {task.get('title', task_id)}",
            body=(
                f"Auto-generated by DevelopmentAgent\n\n"
                f"**Task ID:** {task_id}\n"
                f"**Description:** {task.get('description', '')}\n"
            ),
        )

        return {
            "branch": branch,
            "backend_file": backend_path,
            "frontend_file": frontend_path,
            "pr_url": pr.get("html_url"),
            "commits": commit_results,
        }
